# DP 2nd Average grade
classes = int(input("how many classes do you have: "))
if classes == 7:
    period1 = int(input("what is your grade for period 1: "))
    period2 = int(input("what is your grade for period 2: "))
    period3 = int(input("what is your grade for period 3: "))
    period4 = int(input("what is your grade for period 4: "))
    period5 = int(input("what is your grade for period 5: "))
    period6 = int(input("what is your grade for period 6: "))
    period7 = int(input("what is your grade for period 7: "))
    avgrade = float((period1 + period2 + period3 + period4 + period5 + period6 + period7) / 7)
    print(round(avgrade, 2))
elif classes == 6:
    period1 = int(input("what is your grade for period 1: "))
    period2 = int(input("what is your grade for period 2: "))
    period3 = int(input("what is your grade for period 3: "))
    period4 = int(input("what is your grade for period 4: "))
    period5 = int(input("what is your grade for period 5: "))
    period6 = int(input("what is your grade for period 6: "))
    avgrade = float((period1 + period2 + period3 + period4 + period5 + period6) / 6)
    print(round(avgrade, 2))
elif classes == 5:
    period1 = int(input("what is your grade for period 1: "))
    period2 = int(input("what is your grade for period 2: "))
    period3 = int(input("what is your grade for period 3: "))
    period4 = int(input("what is your grade for period 4: "))
    period5 = int(input("what is your grade for period 5: "))
    avgrade = float((period1 + period2 + period3 + period4 + period5) / 5)
    print(round(avgrade, 2))

